-- Enable pgvector extension for embeddings
create extension if not exists vector;

-- USERS TABLE
create table public.users (
  id uuid references auth.users not null primary key,
  email text unique not null,
  resume_url text,
  preferences jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- JOB SOURCES TABLE
create table public.job_sources (
  id bigint generated by default as identity primary key,
  name text not null unique, -- 'LinkedIn', 'Indeed', 'Naukri', 'Glassdoor'
  base_url text not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- JOBS TABLE
create table public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  location text,
  description text,
  url text unique not null,
  source_id bigint references public.job_sources(id),
  posted_date timestamp with time zone,
  is_active boolean default true,
  embedding vector(384), -- using all-MiniLM-L6-v2 (384 dim) or L12 (384 dim)
  job_fingerprint text, -- hash for quick deduplication checks
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RESUMES TABLE
create table public.resumes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  content_text text,
  embedding vector(384), -- matches job embedding dimension
  file_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- JOB MATCHES TABLE
create table public.job_matches (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  job_id bigint references public.jobs(id) not null,
  similarity_score float, -- 0 to 1
  status text default 'new', -- 'new', 'applied', 'rejected', 'saved'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, job_id)
);

-- SCRAPING LOGS TABLE
create table public.scraping_logs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null, -- 'success', 'failed'
  jobs_found integer default 0,
  error_message text,
  duration_ms integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- NOTIFICATIONS TABLE
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  type text not null, -- 'email', 'telegram'
  message text,
  sent_at timestamp with time zone,
  status text default 'pending' -- 'pending', 'sent', 'failed'
);

-- INDEXES
create index on public.jobs using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create index idx_jobs_url on public.jobs(url);
create index idx_jobs_fingerprint on public.jobs(job_fingerprint);
create index idx_matches_user on public.job_matches(user_id);

-- RLS POLICIES (Simplified for demo)
alter table public.jobs enable row level security;
create policy "Allow public read jobs" on public.jobs for select using (true);

alter table public.job_sources enable row level security;
create policy "Allow public read sources" on public.job_sources for select using (true);

alter table public.resumes enable row level security;
create policy "Allow individual resume access" on public.resumes for all using (true); -- Simplified

